//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meninx.Productify.Web.ProductifyServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductContract", Namespace="http://schemas.datacontract.org/2004/07/Meninx.Productify.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class ProductContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Meninx.Productify.Web.ProductifyServiceReference.AttributeContract[] AttributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Meninx.Productify.Web.ProductifyServiceReference.AttributeContract[] Attributes {
            get {
                return this.AttributesField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributesField, value) != true)) {
                    this.AttributesField = value;
                    this.RaisePropertyChanged("Attributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributeContract", Namespace="http://schemas.datacontract.org/2004/07/Meninx.Productify.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class AttributeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttributeTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AttributeTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttributeTypeId {
            get {
                return this.AttributeTypeIdField;
            }
            set {
                if ((this.AttributeTypeIdField.Equals(value) != true)) {
                    this.AttributeTypeIdField = value;
                    this.RaisePropertyChanged("AttributeTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AttributeTypeName {
            get {
                return this.AttributeTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AttributeTypeNameField, value) != true)) {
                    this.AttributeTypeNameField = value;
                    this.RaisePropertyChanged("AttributeTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttributeTypeContract", Namespace="http://schemas.datacontract.org/2004/07/Meninx.Productify.Service.Contracts")]
    [System.SerializableAttribute()]
    public partial class AttributeTypeContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DataTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DataTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DataTypeId {
            get {
                return this.DataTypeIdField;
            }
            set {
                if ((this.DataTypeIdField.Equals(value) != true)) {
                    this.DataTypeIdField = value;
                    this.RaisePropertyChanged("DataTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DataTypeName {
            get {
                return this.DataTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DataTypeNameField, value) != true)) {
                    this.DataTypeNameField = value;
                    this.RaisePropertyChanged("DataTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductifyServiceReference.IProductifyService")]
    public interface IProductifyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetData", ReplyAction="http://tempuri.org/IProductifyService/GetDataResponse")]
        Meninx.Productify.Web.ProductifyServiceReference.ProductContract[] GetData(string productName, string code, System.Nullable<int> price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetData", ReplyAction="http://tempuri.org/IProductifyService/GetDataResponse")]
        System.Threading.Tasks.Task<Meninx.Productify.Web.ProductifyServiceReference.ProductContract[]> GetDataAsync(string productName, string code, System.Nullable<int> price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/AddProduct", ReplyAction="http://tempuri.org/IProductifyService/AddProductResponse")]
        void AddProduct(Meninx.Productify.Web.ProductifyServiceReference.ProductContract product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/AddProduct", ReplyAction="http://tempuri.org/IProductifyService/AddProductResponse")]
        System.Threading.Tasks.Task AddProductAsync(Meninx.Productify.Web.ProductifyServiceReference.ProductContract product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/UpdateProduct", ReplyAction="http://tempuri.org/IProductifyService/UpdateProductResponse")]
        void UpdateProduct(Meninx.Productify.Web.ProductifyServiceReference.ProductContract product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/UpdateProduct", ReplyAction="http://tempuri.org/IProductifyService/UpdateProductResponse")]
        System.Threading.Tasks.Task UpdateProductAsync(Meninx.Productify.Web.ProductifyServiceReference.ProductContract product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/RemoveProduct", ReplyAction="http://tempuri.org/IProductifyService/RemoveProductResponse")]
        void RemoveProduct(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/RemoveProduct", ReplyAction="http://tempuri.org/IProductifyService/RemoveProductResponse")]
        System.Threading.Tasks.Task RemoveProductAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetProductAttributes", ReplyAction="http://tempuri.org/IProductifyService/GetProductAttributesResponse")]
        Meninx.Productify.Web.ProductifyServiceReference.AttributeContract[] GetProductAttributes(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetProductAttributes", ReplyAction="http://tempuri.org/IProductifyService/GetProductAttributesResponse")]
        System.Threading.Tasks.Task<Meninx.Productify.Web.ProductifyServiceReference.AttributeContract[]> GetProductAttributesAsync(int productId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetXml", ReplyAction="http://tempuri.org/IProductifyService/GetXmlResponse")]
        System.IO.FileInfo GetXml(string productName, string code, System.Nullable<int> price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetXml", ReplyAction="http://tempuri.org/IProductifyService/GetXmlResponse")]
        System.Threading.Tasks.Task<System.IO.FileInfo> GetXmlAsync(string productName, string code, System.Nullable<int> price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetJson", ReplyAction="http://tempuri.org/IProductifyService/GetJsonResponse")]
        System.IO.FileInfo GetJson(string productName, string code, System.Nullable<int> price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetJson", ReplyAction="http://tempuri.org/IProductifyService/GetJsonResponse")]
        System.Threading.Tasks.Task<System.IO.FileInfo> GetJsonAsync(string productName, string code, System.Nullable<int> price);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetAttributeTypes", ReplyAction="http://tempuri.org/IProductifyService/GetAttributeTypesResponse")]
        Meninx.Productify.Web.ProductifyServiceReference.AttributeTypeContract[] GetAttributeTypes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductifyService/GetAttributeTypes", ReplyAction="http://tempuri.org/IProductifyService/GetAttributeTypesResponse")]
        System.Threading.Tasks.Task<Meninx.Productify.Web.ProductifyServiceReference.AttributeTypeContract[]> GetAttributeTypesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductifyServiceChannel : Meninx.Productify.Web.ProductifyServiceReference.IProductifyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductifyServiceClient : System.ServiceModel.ClientBase<Meninx.Productify.Web.ProductifyServiceReference.IProductifyService>, Meninx.Productify.Web.ProductifyServiceReference.IProductifyService {
        
        public ProductifyServiceClient() {
        }
        
        public ProductifyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductifyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductifyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductifyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Meninx.Productify.Web.ProductifyServiceReference.ProductContract[] GetData(string productName, string code, System.Nullable<int> price) {
            return base.Channel.GetData(productName, code, price);
        }
        
        public System.Threading.Tasks.Task<Meninx.Productify.Web.ProductifyServiceReference.ProductContract[]> GetDataAsync(string productName, string code, System.Nullable<int> price) {
            return base.Channel.GetDataAsync(productName, code, price);
        }
        
        public void AddProduct(Meninx.Productify.Web.ProductifyServiceReference.ProductContract product) {
            base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task AddProductAsync(Meninx.Productify.Web.ProductifyServiceReference.ProductContract product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public void UpdateProduct(Meninx.Productify.Web.ProductifyServiceReference.ProductContract product) {
            base.Channel.UpdateProduct(product);
        }
        
        public System.Threading.Tasks.Task UpdateProductAsync(Meninx.Productify.Web.ProductifyServiceReference.ProductContract product) {
            return base.Channel.UpdateProductAsync(product);
        }
        
        public void RemoveProduct(int productId) {
            base.Channel.RemoveProduct(productId);
        }
        
        public System.Threading.Tasks.Task RemoveProductAsync(int productId) {
            return base.Channel.RemoveProductAsync(productId);
        }
        
        public Meninx.Productify.Web.ProductifyServiceReference.AttributeContract[] GetProductAttributes(int productId) {
            return base.Channel.GetProductAttributes(productId);
        }
        
        public System.Threading.Tasks.Task<Meninx.Productify.Web.ProductifyServiceReference.AttributeContract[]> GetProductAttributesAsync(int productId) {
            return base.Channel.GetProductAttributesAsync(productId);
        }
        
        public System.IO.FileInfo GetXml(string productName, string code, System.Nullable<int> price) {
            return base.Channel.GetXml(productName, code, price);
        }
        
        public System.Threading.Tasks.Task<System.IO.FileInfo> GetXmlAsync(string productName, string code, System.Nullable<int> price) {
            return base.Channel.GetXmlAsync(productName, code, price);
        }
        
        public System.IO.FileInfo GetJson(string productName, string code, System.Nullable<int> price) {
            return base.Channel.GetJson(productName, code, price);
        }
        
        public System.Threading.Tasks.Task<System.IO.FileInfo> GetJsonAsync(string productName, string code, System.Nullable<int> price) {
            return base.Channel.GetJsonAsync(productName, code, price);
        }
        
        public Meninx.Productify.Web.ProductifyServiceReference.AttributeTypeContract[] GetAttributeTypes() {
            return base.Channel.GetAttributeTypes();
        }
        
        public System.Threading.Tasks.Task<Meninx.Productify.Web.ProductifyServiceReference.AttributeTypeContract[]> GetAttributeTypesAsync() {
            return base.Channel.GetAttributeTypesAsync();
        }
    }
}
